### ISSUE TITLE
citeproc_with_e4x syntax errors on load

### ISSUE THREAD

**Issue by amardesi** [Juris-M/citeproc-js#45]
In `tests/runners/rhino-bundled.js`
the command
`load("./citeproc_with_e4x.js");`
is failing with this output

```
js: "./citeproc_with_e4x.js", line 14488: missing ; after for-loop initializer
js:         for (var key of Object.keys(_nestingData)) {
js: .......................^
js: "./citeproc_with_e4x.js", line 14489: missing ; before statement
js:             if (_nestingData[key].type === "quote") {
js: ....................................................^
js: "./citeproc_with_e4x.js", line 14493: invalid return
js:         return ret;
js: ..............^
js: "./citeproc_with_e4x.js", line 14494: syntax error
js:     }();
js: ....^
js: "./citeproc_with_e4x.js", line 14497: missing ; after for-loop initializer
js:         for (var key of Object.keys(_nestingData)) {
js: .......................^
js: "./citeproc_with_e4x.js", line 14498: missing ; before statement
js:             if (_nestingData[key].type === "nocase") continue;
js: .............................................................^
js: "./citeproc_with_e4x.js", line 14505: invalid return
js:         return ret;
js: ..............^
js: "./citeproc_with_e4x.js", line 14506: syntax error
js:     }();
js: ....^
js: "./citeproc_with_e4x.js", line 14520: missing ; after for-loop initializer
js:         for (var key of Object.keys(_nestingData)) {
js: .......................^
js: "./citeproc_with_e4x.js", line 14521: missing ; before statement
js:             if (_nestingData[opener].type !== "quote" || !_nestingData[opener]) {
js: ................................................................................^
js: "./citeproc_with_e4x.js", line 14522: syntax error
js:                 openers.push(key);
js: ........................^
js: "./citeproc_with_e4x.js", line 14524: syntax error
js:         }
js: ........^
js: "./citeproc_with_e4x.js", line 14527: invalid return
js:         return ret;
js: ..............^
js: "./citeproc_with_e4x.js", line 14528: syntax error
js:     }
js: ....^
js: "./citeproc_with_e4x.js", line 14531: missing ; after for-loop initializer
js:         for (var key of Object.keys(_nestingData)) {
js: .......................^
js: "./citeproc_with_e4x.js", line 14534: invalid return
js:         return ret;
js: ..............^
js: "./citeproc_with_e4x.js", line 14535: syntax error
js:     }()
js: ....^
js: "./citeproc_with_e4x.js", line 14544: missing ; after for-loop initializer
js:         for (var closer of Object.keys(vals)) {
js: ..........................^
js: "./citeproc_with_e4x.js", line 14545: syntax error
js:             closers.push(closer);
js: ....................^
js: "./citeproc_with_e4x.js", line 14548: invalid return
js:         return {
js: ..............^
js: "./citeproc_with_e4x.js", line 14550: missing ; before statement
js:             splitAll: new RegExp("(?:" + all + ")", "g"),
js: .....................^
js: "./citeproc_with_e4x.js", line 14551: syntax error
js:             open: new RegExp("(^(?:" + openers.map(function(str){return str.replace("(", "\\(")}).join("|") + ")$)"),
js: .................^
js: "./citeproc_with_e4x.js", line 14552: syntax error
js:             close: new RegExp("(^(?:" + closers.join("|") + ")$)"),
js: ..................^
js: "./citeproc_with_e4x.js", line 14554: syntax error
js:     }();
js: ......^
js: "./citeproc_with_e4x.js", line 14868: syntax error
js: }
js: ^
js: "./citeproc_with_e4x.js", line 14869: syntax error
js: CSL.Output.Formatters = new function () {
js: ....^
js: "./citeproc_with_e4x.js", line 14870: syntax error
js:     this.passthrough = passthrough;
js: .........^
js: "./citeproc_with_e4x.js", line 15166: syntax error
js: }
js: ^
js: "./citeproc_with_e4x.js", line 15167: syntax error
js: CSL.Output.Formats = function () {};
js: ....^
Testing with rhino: UTF-8
477 tests to run in 41 groups
------------------------------------------------------------
GROUP "std.plural" has 2 tests to run
ReferenceError: "CSL" is not defined.
	ERROR IN:
		 (function () {var test = new StdRhinoTest("plural_AffiliationSpoofingIsPluralWithNames", "rhino");doh.assertEqual(test.result, test.run());})
org.mozilla.javascript.EcmaError: ReferenceError: "CSL" is not defined.
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3785)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3763)
	at org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:3848)
	at org.mozilla.javascript.ScriptRuntime.nameOrFunction(ScriptRuntime.java:1847)
	at org.mozilla.javascript.ScriptRuntime.name(ScriptRuntime.java:1786)
	at org.mozilla.javascript.gen.__src_test_runner_js_3._c_anonymous_1(Unknown Source)
	at org.mozilla.javascript.gen.__src_test_runner_js_3.call(Unknown Source)
	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:369)
	at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2440)
	at org.mozilla.javascript.gen.____tests_bundled_plural_js_9._c_anonymous_1(Unknown Source)
	at org.mozilla.javascript.gen.____tests_bundled_plural_js_9.call(Unknown Source)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
	at org.mozilla.javascript.gen.____dojo_util_doh_runner_js_5._c_anonymous_62(Unknown Source)
	at org.mozilla.javascript.gen.____dojo_util_doh_runner_js_5.call(Unknown Source)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)
	at org.mozilla.javascript.gen.____dojo_util_doh_runner_js_5._c_anonymous_69(Unknown Source)
	at org.mozilla.javascript.gen.____dojo_util_doh_runner_js_5.call(Unknown Source)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
	at org.mozilla.javascript.gen.____dojo_util_doh_runner_js_5._c_anonymous_74(Unknown Source)
	at org.mozilla.javascript.gen.____dojo_util_doh_runner_js_5.call(Unknown Source)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
	at org.mozilla.javascript.gen.__tests_runners_run_js_4._c_script_0(Unknown Source)
	at org.mozilla.javascript.gen.__tests_runners_run_js_4.call(Unknown Source)
	at org.mozilla.javascript.gen.__tests_runners_run_js_4.exec(Unknown Source)
	at org.mozilla.javascript.tools.shell.Main.evaluateScript(Main.java:654)
	at org.mozilla.javascript.tools.shell.Main.processFileSecure(Main.java:552)
	at org.mozilla.javascript.tools.shell.Main.processFile(Main.java:507)
	at org.mozilla.javascript.tools.shell.Global.load(Global.java:282)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
	at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:413)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:97)
	at org.mozilla.javascript.gen.tests_runners_rhino_bundled_js_1._c_script_0(Unknown Source)
	at org.mozilla.javascript.gen.tests_runners_rhino_bundled_js_1.call(Unknown Source)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:426)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3178)
	at org.mozilla.javascript.gen.tests_runners_rhino_bundled_js_1.call(Unknown Source)
	at org.mozilla.javascript.gen.tests_runners_rhino_bundled_js_1.exec(Unknown Source)
	at org.mozilla.javascript.tools.shell.Main.evaluateScript(Main.java:654)
	at org.mozilla.javascript.tools.shell.Main.processFileSecure(Main.java:552)
	at org.mozilla.javascript.tools.shell.Main.processFile(Main.java:507)
	at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:499)
	at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:215)
	at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:134)
	at org.mozilla.javascript.Context.call(Context.java:521)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:535)
	at org.mozilla.javascript.tools.shell.Main.exec(Main.java:198)
	at org.mozilla.javascript.tools.shell.Main.main(Main.java:174)
```

**Comment by fbennett** [comment]
Hmm. Looks like you're running Rhino, and it doesn't support es6 constructs? As we can now parse serialized XML directly in the normal version, I wonder if it might work to switch to that?  Broad compatibility is important, but I don't relish the idea of downgrading syntax throughout the processor.

**Comment by miguelsm** [comment]
I had the same problem with the normal version when running citeproc in Google Apps Script:
https://github.com/Juris-M/citeproc-js/pull/38

One can always use Babel, but I ran into other problems there as explained in the PR comments. I intend to maintain an ES5 compatible version in my fork for that reason (at least until GAS supports ES6).

**Comment by fbennett** [comment]
Ah - of course. The syntax errors are not thrown for E4X errors here, but for ES6.

As @miguelsm has already posted a pull request with ES5 changes, I'll try to get those into a release this week.

**Comment by fbennett** [comment]
Closing: The pull request by @miguelsm has been adopted (after too much delay, I know), and the processor is now pure ES5.
